version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"
    PROJECT_NAME: "etl-scomics"

phases:
  pre_build:
    commands:
      - echo "Intializing Terraform..."
      - cd terraform
      - terraform init 
      
  build:
    commands:
      - echo "Deploying infrastructure..."
      - terraform apply -auto-approve || { echo "Terraform apply failed!"; exit 1; }
      - SCRIPTS_BUCKET=$(terraform output -raw scripts_bucket)
      - GLUE_JOB_NAME=$(terraform output -raw glue_job_name)
      - cd ..
      
      - echo "Uploading scripts..."
      - aws s3 cp glue_scripts/test_hello_world.py s3://$SCRIPTS_BUCKET/
      
      - echo "Testing job..."
      - aws glue start-job-run --job-name $GLUE_JOB_NAME

  post_build:
    commands:
      - echo "Build completed!"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'terraform/.terraform/**/*'
